/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* src = "convert_to_v/adder.v:1.1-46.10" *)
(* top =  1  *)
(* dynports =  1  *)
(* hdlname = "adder" *)
module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  (* src = "convert_to_v/adder.v:12.27-12.31" *)
  input [7:0] srca;
  wire [7:0] srca;
  (* src = "convert_to_v/adder.v:13.27-13.31" *)
  input [7:0] srcb;
  wire [7:0] srcb;
  (* src = "convert_to_v/adder.v:14.13-14.16" *)
  input cin;
  wire cin;
  (* src = "convert_to_v/adder.v:15.13-15.22" *)
  input is_signed;
  wire is_signed;
  (* src = "convert_to_v/adder.v:16.28-16.34" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "convert_to_v/adder.v:17.14-17.18" *)
  output cout;
  wire cout;
  (* src = "convert_to_v/adder.v:18.14-18.20" *)
  output zero_f;
  wire zero_f;
  (* src = "convert_to_v/adder.v:19.14-19.18" *)
  output ov_f;
  wire ov_f;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* src = "convert_to_v/adder.v:23.17-23.18" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [8:0] c;
  (* src = "convert_to_v/adder.v:21.137-21.138" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30" *)
  wire [31:0] g;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27" *)
  wire [27:0] p;
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(srca[0]),
    .B(srcb[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__maj3_1 _20_ (
    .A(srca[0]),
    .B(srcb[0]),
    .C(cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(srca[1]),
    .B(srcb[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _22_ (
    .A(srca[1]),
    .B(srcb[1]),
    .C(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(srca[2]),
    .B(srcb[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _24_ (
    .A(srca[2]),
    .B(srcb[2]),
    .C(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _25_ (
    .A(srca[3]),
    .B(srcb[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _26_ (
    .A(srca[3]),
    .B(srcb[3]),
    .C(_05_),
    .X(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(srca[4]),
    .B(srcb[4]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__maj3_1 _28_ (
    .A(srca[4]),
    .B(srcb[4]),
    .C(_07_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _29_ (
    .A(srca[5]),
    .B(srcb[5]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__maj3_1 _30_ (
    .A(srca[5]),
    .B(srcb[5]),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(srca[6]),
    .B(srcb[6]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(_11_),
    .B(_12_),
    .Y(result[6])
  );
  sky130_fd_sc_hd__maj3_1 _33_ (
    .A(srca[6]),
    .B(srcb[6]),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(srca[7]),
    .B(srcb[7]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(srca[7]),
    .B(srcb[7]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(_13_),
    .B(_15_),
    .Y(result[7])
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(_07_),
    .B(_08_),
    .Y(result[4])
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(_09_),
    .B(_10_),
    .Y(result[5])
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(_03_),
    .B(_04_),
    .Y(result[2])
  );
  sky130_fd_sc_hd__xnor2_1 _40_ (
    .A(_05_),
    .B(_06_),
    .Y(result[3])
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(cin),
    .B(_00_),
    .Y(result[0])
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_01_),
    .B(_02_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__or4_1 _43_ (
    .A(result[4]),
    .B(result[5]),
    .C(result[2]),
    .D(result[1]),
    .X(_16_)
  );
  sky130_fd_sc_hd__or3_1 _44_ (
    .A(result[6]),
    .B(result[3]),
    .C(result[0]),
    .X(_17_)
  );
  sky130_fd_sc_hd__nor3_1 _45_ (
    .A(result[7]),
    .B(_16_),
    .C(_17_),
    .Y(zero_f)
  );
  sky130_fd_sc_hd__maj3_1 _46_ (
    .A(srca[7]),
    .B(srcb[7]),
    .C(_13_),
    .X(cout)
  );
  sky130_fd_sc_hd__nand2_1 _47_ (
    .A(is_signed),
    .B(_13_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__mux2_1 _48_ (
    .A0(_14_),
    .A1(cout),
    .S(_18_),
    .X(ov_f)
  );
  assign { p[27:24], p[17:16], p[8] } = { p[19:18], p[9], p[0], p[9], p[0], p[0] };
  assign { c[8], c[0] } = { cout, cin };
  assign { g[31:24], g[19:16], g[9:8], g[0] } = { cout, c[7:1], c[4:1], c[2:1], c[1] };
endmodule
