/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* src = "convert_to_v/adder.v:1.1-46.10" *)
(* top =  1  *)
(* dynports =  1  *)
(* hdlname = "adder" *)
module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  (* src = "convert_to_v/adder.v:12.27-12.31" *)
  input [31:0] srca;
  wire [31:0] srca;
  (* src = "convert_to_v/adder.v:13.27-13.31" *)
  input [31:0] srcb;
  wire [31:0] srcb;
  (* src = "convert_to_v/adder.v:14.13-14.16" *)
  input cin;
  wire cin;
  (* src = "convert_to_v/adder.v:15.13-15.22" *)
  input is_signed;
  wire is_signed;
  (* src = "convert_to_v/adder.v:16.28-16.34" *)
  output [31:0] result;
  wire [31:0] result;
  (* src = "convert_to_v/adder.v:17.14-17.18" *)
  output cout;
  wire cout;
  (* src = "convert_to_v/adder.v:18.14-18.20" *)
  output zero_f;
  wire zero_f;
  (* src = "convert_to_v/adder.v:19.14-19.18" *)
  output ov_f;
  wire ov_f;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  (* src = "convert_to_v/adder.v:23.17-23.18" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [32:0] c;
  (* src = "convert_to_v/adder.v:21.137-21.138" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190" *)
  wire [191:0] g;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175" *)
  wire [175:0] p;
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(srca[30]),
    .B(srcb[30]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(srca[30]),
    .B(srcb[30]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _183_ (
    .A(_000_),
    .SLEEP(_001_),
    .X(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _184_ (
    .A(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(srca[25]),
    .B(srcb[25]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(srca[25]),
    .B(srcb[25]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _187_ (
    .A(_004_),
    .SLEEP(_005_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(srca[21]),
    .B(srcb[21]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _189_ (
    .A(srca[19]),
    .SLEEP(srcb[19]),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _190_ (
    .A(srca[17]),
    .B(srcb[17]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _191_ (
    .A(srca[15]),
    .SLEEP(srcb[15]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(srca[13]),
    .B(srcb[13]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _193_ (
    .A(srca[11]),
    .SLEEP(srcb[11]),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(srca[10]),
    .B(srcb[10]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _195_ (
    .A(srca[10]),
    .SLEEP(srcb[10]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(srca[9]),
    .B(srcb[9]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(srca[9]),
    .B(srcb[9]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and2_0 _199_ (
    .A(srca[8]),
    .B(srcb[8]),
    .X(_018_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _200_ (
    .A(srca[7]),
    .SLEEP(srcb[7]),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_0 _201_ (
    .A(srca[7]),
    .B(srcb[7]),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _202_ (
    .A(srca[7]),
    .B(srcb[7]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _203_ (
    .A(srca[6]),
    .SLEEP(srcb[6]),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(srca[6]),
    .B(srcb[6]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(srca[5]),
    .B(srcb[5]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(srca[4]),
    .B(srcb[4]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _207_ (
    .A(srca[4]),
    .B(srcb[4]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(srca[3]),
    .B(srcb[3]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _209_ (
    .A(srca[3]),
    .SLEEP(srcb[3]),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(srca[2]),
    .B(srcb[2]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _211_ (
    .A(srca[2]),
    .SLEEP(srcb[2]),
    .X(_030_)
  );
  sky130_fd_sc_hd__and2_0 _212_ (
    .A(srca[1]),
    .B(srcb[1]),
    .X(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _213_ (
    .A(srca[0]),
    .B(srcb[0]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__maj3_1 _214_ (
    .A(srca[0]),
    .B(srcb[0]),
    .C(cin),
    .X(_033_)
  );
  sky130_fd_sc_hd__xor2_1 _215_ (
    .A(srca[1]),
    .B(srcb[1]),
    .X(_034_)
  );
  sky130_fd_sc_hd__a21oi_1 _216_ (
    .A1(_033_),
    .A2(_034_),
    .B1(_031_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a221o_1 _217_ (
    .A1(srca[2]),
    .A2(srcb[2]),
    .B1(_033_),
    .B2(_034_),
    .C1(_031_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand3_1 _218_ (
    .A(_028_),
    .B(_030_),
    .C(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(_027_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a31oi_1 _220_ (
    .A1(_025_),
    .A2(_027_),
    .A3(_037_),
    .B1(_026_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a311oi_1 _221_ (
    .A1(_025_),
    .A2(_027_),
    .A3(_037_),
    .B1(_026_),
    .C1(_024_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21o_1 _222_ (
    .A1(srca[5]),
    .A2(srcb[5]),
    .B1(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a221o_1 _223_ (
    .A1(srca[6]),
    .A2(srcb[6]),
    .B1(srca[5]),
    .B2(srcb[5]),
    .C1(_040_),
    .X(_042_)
  );
  sky130_fd_sc_hd__and2_0 _224_ (
    .A(_022_),
    .B(_042_),
    .X(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _225_ (
    .A1(_019_),
    .A2(_043_),
    .B1(_020_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _226_ (
    .A(srca[8]),
    .B(srcb[8]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a311oi_1 _227_ (
    .A1(_019_),
    .A2(_022_),
    .A3(_042_),
    .B1(_020_),
    .C1(_018_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _228_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor3_1 _229_ (
    .A(_017_),
    .B(_045_),
    .C(_046_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _230_ (
    .A(_018_),
    .B(_045_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o31a_1 _231_ (
    .A1(_017_),
    .A2(_045_),
    .A3(_046_),
    .B1(_016_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(srca[11]),
    .B(srcb[11]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o211ai_1 _233_ (
    .A1(_015_),
    .A2(_050_),
    .B1(_051_),
    .C1(_013_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(_012_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(srca[12]),
    .B(srcb[12]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _236_ (
    .A(srca[12]),
    .B(srcb[12]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _237_ (
    .A(_054_),
    .SLEEP(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(srca[13]),
    .B(srcb[13]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_054_),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a31oi_1 _240_ (
    .A1(_012_),
    .A2(_052_),
    .A3(_056_),
    .B1(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2b_1 _241_ (
    .A_N(_011_),
    .B(_057_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(_011_),
    .B(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(srca[14]),
    .B(srcb[14]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(srca[14]),
    .B(srcb[14]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _245_ (
    .A(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(_062_),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(srca[15]),
    .B(srcb[15]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o311ai_0 _248_ (
    .A1(_011_),
    .A2(_059_),
    .A3(_063_),
    .B1(_066_),
    .C1(_062_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(_010_),
    .B(_066_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _250_ (
    .A(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(_010_),
    .B(_067_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(srca[16]),
    .B(srcb[16]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(srca[16]),
    .B(srcb[16]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _254_ (
    .A(_071_),
    .SLEEP(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(srca[17]),
    .B(srcb[17]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(_071_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a31oi_1 _257_ (
    .A1(_010_),
    .A2(_067_),
    .A3(_073_),
    .B1(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2b_1 _258_ (
    .A_N(_009_),
    .B(_074_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(_009_),
    .B(_076_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(srca[18]),
    .B(srcb[18]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _261_ (
    .A(srca[18]),
    .B(srcb[18]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(srca[18]),
    .B(srcb[18]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(srca[19]),
    .B(srcb[19]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o311ai_0 _264_ (
    .A1(_009_),
    .A2(_076_),
    .A3(_080_),
    .B1(_082_),
    .C1(_079_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(_008_),
    .B(_082_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(_008_),
    .B(_083_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(srca[20]),
    .B(srcb[20]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _268_ (
    .A(srca[20]),
    .B(srcb[20]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _269_ (
    .A(_086_),
    .SLEEP(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(srca[21]),
    .B(srcb[21]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(_086_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a31oi_1 _272_ (
    .A1(_008_),
    .A2(_083_),
    .A3(_088_),
    .B1(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2b_1 _273_ (
    .A_N(_007_),
    .B(_089_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _274_ (
    .A(_007_),
    .B(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(srca[23]),
    .B(srcb[23]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(srca[23]),
    .B(srcb[23]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _277_ (
    .A(_094_),
    .SLEEP(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(srca[22]),
    .B(srcb[22]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(srca[22]),
    .B(srcb[22]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _280_ (
    .A(srca[22]),
    .SLEEP(srcb[22]),
    .X(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(_097_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand3_1 _282_ (
    .A(_096_),
    .B(_097_),
    .C(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21a_1 _283_ (
    .A1(_095_),
    .A2(_097_),
    .B1(_094_),
    .X(_102_)
  );
  sky130_fd_sc_hd__o31ai_1 _284_ (
    .A1(_007_),
    .A2(_091_),
    .A3(_101_),
    .B1(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(srca[24]),
    .B(srcb[24]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _286_ (
    .A(srca[24]),
    .B(srcb[24]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _287_ (
    .A(_104_),
    .SLEEP(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(_004_),
    .A2(_104_),
    .B1(_005_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a31oi_1 _289_ (
    .A1(_006_),
    .A2(_103_),
    .A3(_106_),
    .B1(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(srca[26]),
    .B(srcb[26]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(srca[26]),
    .B(srcb[26]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _292_ (
    .A(_109_),
    .SLEEP(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(srca[27]),
    .B(srcb[27]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(srca[27]),
    .B(srcb[27]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xnor2_1 _295_ (
    .A(srca[27]),
    .B(srcb[27]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand3b_1 _296_ (
    .A_N(_113_),
    .B(_111_),
    .C(_112_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o221a_1 _297_ (
    .A1(_109_),
    .A2(_113_),
    .B1(_115_),
    .B2(_108_),
    .C1(_112_),
    .X(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(srca[28]),
    .B(srcb[28]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _299_ (
    .A(srca[28]),
    .B(srcb[28]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(srca[29]),
    .B(srcb[29]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor2_1 _301_ (
    .A(srca[29]),
    .B(srcb[29]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o211ai_1 _302_ (
    .A1(srca[29]),
    .A2(srcb[29]),
    .B1(srca[28]),
    .C1(srcb[28]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o311ai_0 _303_ (
    .A1(_116_),
    .A2(_118_),
    .A3(_120_),
    .B1(_121_),
    .C1(_119_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _304_ (
    .A(_003_),
    .B(_122_),
    .Y(result[30])
  );
  sky130_fd_sc_hd__nand2_1 _305_ (
    .A(_012_),
    .B(_051_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(_013_),
    .B(_016_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xnor2_1 _307_ (
    .A(srca[9]),
    .B(srcb[9]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21ai_0 _308_ (
    .A1(_048_),
    .A2(_124_),
    .B1(_014_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o2111ai_1 _309_ (
    .A1(_048_),
    .A2(_124_),
    .B1(_051_),
    .C1(_012_),
    .D1(_014_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a31oi_1 _310_ (
    .A1(_051_),
    .A2(_054_),
    .A3(_127_),
    .B1(_055_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a311oi_1 _311_ (
    .A1(_051_),
    .A2(_054_),
    .A3(_127_),
    .B1(_060_),
    .C1(_055_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(_057_),
    .B(_062_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _313_ (
    .A1(_129_),
    .A2(_130_),
    .B1(_064_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o211ai_1 _314_ (
    .A1(_129_),
    .A2(_130_),
    .B1(_064_),
    .C1(_069_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a31oi_1 _315_ (
    .A1(_066_),
    .A2(_071_),
    .A3(_132_),
    .B1(_072_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a311o_1 _316_ (
    .A1(_066_),
    .A2(_071_),
    .A3(_132_),
    .B1(_077_),
    .C1(_072_),
    .X(_134_)
  );
  sky130_fd_sc_hd__a31oi_1 _317_ (
    .A1(_074_),
    .A2(_079_),
    .A3(_134_),
    .B1(_080_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a311o_1 _318_ (
    .A1(_074_),
    .A2(_079_),
    .A3(_134_),
    .B1(_084_),
    .C1(_080_),
    .X(_136_)
  );
  sky130_fd_sc_hd__a31oi_1 _319_ (
    .A1(_082_),
    .A2(_086_),
    .A3(_136_),
    .B1(_087_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a311o_1 _320_ (
    .A1(_082_),
    .A2(_086_),
    .A3(_136_),
    .B1(_092_),
    .C1(_087_),
    .X(_138_)
  );
  sky130_fd_sc_hd__a31oi_1 _321_ (
    .A1(_089_),
    .A2(_097_),
    .A3(_138_),
    .B1(_098_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(_096_),
    .B(_106_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a311oi_1 _323_ (
    .A1(_089_),
    .A2(_097_),
    .A3(_138_),
    .B1(_140_),
    .C1(_098_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _324_ (
    .A1(_094_),
    .A2(_105_),
    .B1(_104_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_141_),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o211ai_1 _326_ (
    .A1(_141_),
    .A2(_142_),
    .B1(_006_),
    .C1(_111_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21ai_0 _327_ (
    .A1(_004_),
    .A2(_110_),
    .B1(_109_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(_144_),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a211o_1 _330_ (
    .A1(_144_),
    .A2(_146_),
    .B1(_114_),
    .C1(_118_),
    .X(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(_112_),
    .B(_117_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _332_ (
    .A1(srca[28]),
    .A2(srcb[28]),
    .B1(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(_148_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a211oi_1 _334_ (
    .A1(_148_),
    .A2(_150_),
    .B1(_003_),
    .C1(_120_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _335_ (
    .A1(_001_),
    .A2(_119_),
    .B1(_000_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(srca[31]),
    .B(srcb[31]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(srca[31]),
    .B(srcb[31]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _338_ (
    .A(_154_),
    .SLEEP(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd__or3_1 _339_ (
    .A(_152_),
    .B(_153_),
    .C(_156_),
    .X(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _340_ (
    .A1(_152_),
    .A2(_153_),
    .B1(_156_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__and2_0 _341_ (
    .A(_157_),
    .B(_158_),
    .X(result[31])
  );
  sky130_fd_sc_hd__xor2_1 _342_ (
    .A(_116_),
    .B(_118_),
    .X(result[28])
  );
  sky130_fd_sc_hd__xnor2_1 _343_ (
    .A(_120_),
    .B(_151_),
    .Y(result[29])
  );
  sky130_fd_sc_hd__xnor2_1 _344_ (
    .A(_108_),
    .B(_111_),
    .Y(result[26])
  );
  sky130_fd_sc_hd__xnor2_1 _345_ (
    .A(_114_),
    .B(_147_),
    .Y(result[27])
  );
  sky130_fd_sc_hd__xor2_1 _346_ (
    .A(_103_),
    .B(_106_),
    .X(result[24])
  );
  sky130_fd_sc_hd__xnor2_1 _347_ (
    .A(_006_),
    .B(_143_),
    .Y(result[25])
  );
  sky130_fd_sc_hd__xnor2_1 _348_ (
    .A(_093_),
    .B(_100_),
    .Y(result[22])
  );
  sky130_fd_sc_hd__xor2_1 _349_ (
    .A(_096_),
    .B(_139_),
    .X(result[23])
  );
  sky130_fd_sc_hd__xnor2_1 _350_ (
    .A(_085_),
    .B(_088_),
    .Y(result[20])
  );
  sky130_fd_sc_hd__xnor2_1 _351_ (
    .A(_092_),
    .B(_137_),
    .Y(result[21])
  );
  sky130_fd_sc_hd__xnor2_1 _352_ (
    .A(_078_),
    .B(_081_),
    .Y(result[18])
  );
  sky130_fd_sc_hd__xnor2_1 _353_ (
    .A(_084_),
    .B(_135_),
    .Y(result[19])
  );
  sky130_fd_sc_hd__xnor2_1 _354_ (
    .A(_070_),
    .B(_073_),
    .Y(result[16])
  );
  sky130_fd_sc_hd__xnor2_1 _355_ (
    .A(_077_),
    .B(_133_),
    .Y(result[17])
  );
  sky130_fd_sc_hd__xnor2_1 _356_ (
    .A(_061_),
    .B(_065_),
    .Y(result[14])
  );
  sky130_fd_sc_hd__xnor2_1 _357_ (
    .A(_069_),
    .B(_131_),
    .Y(result[15])
  );
  sky130_fd_sc_hd__xnor2_1 _358_ (
    .A(_053_),
    .B(_056_),
    .Y(result[12])
  );
  sky130_fd_sc_hd__xnor2_1 _359_ (
    .A(_060_),
    .B(_128_),
    .Y(result[13])
  );
  sky130_fd_sc_hd__xor2_1 _360_ (
    .A(_015_),
    .B(_050_),
    .X(result[10])
  );
  sky130_fd_sc_hd__xor2_1 _361_ (
    .A(_123_),
    .B(_126_),
    .X(result[11])
  );
  sky130_fd_sc_hd__xnor2_1 _362_ (
    .A(_044_),
    .B(_049_),
    .Y(result[8])
  );
  sky130_fd_sc_hd__xnor2_1 _363_ (
    .A(_047_),
    .B(_125_),
    .Y(result[9])
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(_022_),
    .B(_023_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _365_ (
    .A(_041_),
    .B(_159_),
    .Y(result[6])
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(_019_),
    .B(_021_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__xnor2_1 _367_ (
    .A(_043_),
    .B(_160_),
    .Y(result[7])
  );
  sky130_fd_sc_hd__xnor2_1 _368_ (
    .A(srca[4]),
    .B(srcb[4]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__xnor2_1 _369_ (
    .A(_038_),
    .B(_161_),
    .Y(result[4])
  );
  sky130_fd_sc_hd__xnor2_1 _370_ (
    .A(srca[5]),
    .B(srcb[5]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__xnor2_1 _371_ (
    .A(_039_),
    .B(_162_),
    .Y(result[5])
  );
  sky130_fd_sc_hd__nand2_1 _372_ (
    .A(_029_),
    .B(_030_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__xor2_1 _373_ (
    .A(_035_),
    .B(_163_),
    .X(result[2])
  );
  sky130_fd_sc_hd__nand2_1 _374_ (
    .A(_027_),
    .B(_028_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand3_1 _375_ (
    .A(_030_),
    .B(_036_),
    .C(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a21o_1 _376_ (
    .A1(_030_),
    .A2(_036_),
    .B1(_164_),
    .X(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _377_ (
    .A(_165_),
    .B(_166_),
    .Y(result[3])
  );
  sky130_fd_sc_hd__xnor2_1 _378_ (
    .A(cin),
    .B(_032_),
    .Y(result[0])
  );
  sky130_fd_sc_hd__xor2_1 _379_ (
    .A(_033_),
    .B(_034_),
    .X(result[1])
  );
  sky130_fd_sc_hd__or4_1 _380_ (
    .A(result[2]),
    .B(result[3]),
    .C(result[0]),
    .D(result[1]),
    .X(_167_)
  );
  sky130_fd_sc_hd__nor2_1 _381_ (
    .A(result[6]),
    .B(result[4]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor3_1 _382_ (
    .A(result[7]),
    .B(result[5]),
    .C(_167_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _383_ (
    .A(_168_),
    .B(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__or4_1 _384_ (
    .A(result[10]),
    .B(result[8]),
    .C(result[9]),
    .D(_170_),
    .X(_171_)
  );
  sky130_fd_sc_hd__or4_1 _385_ (
    .A(result[12]),
    .B(result[13]),
    .C(result[11]),
    .D(_171_),
    .X(_172_)
  );
  sky130_fd_sc_hd__nor4_1 _386_ (
    .A(result[16]),
    .B(result[14]),
    .C(result[15]),
    .D(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__or4b_1 _387_ (
    .A(result[18]),
    .B(result[19]),
    .C(result[17]),
    .D_N(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd__or3_1 _388_ (
    .A(result[20]),
    .B(result[21]),
    .C(_174_),
    .X(_175_)
  );
  sky130_fd_sc_hd__or3_1 _389_ (
    .A(result[24]),
    .B(result[23]),
    .C(_175_),
    .X(_176_)
  );
  sky130_fd_sc_hd__or4_1 _390_ (
    .A(result[26]),
    .B(result[25]),
    .C(result[22]),
    .D(_176_),
    .X(_177_)
  );
  sky130_fd_sc_hd__or3_1 _391_ (
    .A(result[28]),
    .B(result[27]),
    .C(_177_),
    .X(_178_)
  );
  sky130_fd_sc_hd__a2111oi_0 _392_ (
    .A1(_157_),
    .A2(_158_),
    .B1(result[29]),
    .C1(_178_),
    .D1(result[30]),
    .Y(zero_f)
  );
  sky130_fd_sc_hd__a21oi_1 _393_ (
    .A1(_000_),
    .A2(_154_),
    .B1(_155_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a31o_1 _394_ (
    .A1(_002_),
    .A2(_122_),
    .A3(_156_),
    .B1(_179_),
    .X(cout)
  );
  sky130_fd_sc_hd__o21ai_0 _395_ (
    .A1(_152_),
    .A2(_153_),
    .B1(is_signed),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xnor2_1 _396_ (
    .A(cout),
    .B(_180_),
    .Y(ov_f)
  );
  assign { p[175:160], p[135:128], p[99:96], p[65:64], p[32] } = { p[143:136], p[103:100], p[67:66], p[33], p[0], p[103:100], p[67:66], p[33], p[0], p[67:66], p[33], p[0], p[33], p[0], p[0] };
  assign { c[32], c[0] } = { cout, cin };
  assign { g[191:160], g[143:128], g[103:96], g[67:64], g[33:32], g[0] } = { cout, c[31:1], c[16:1], c[8:1], c[4:1], c[2:1], c[1] };
endmodule
