/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* src = "convert_to_v/adder.v:1.1-46.10" *)
(* top =  1  *)
(* dynports =  1  *)
(* hdlname = "adder" *)
module adder(srca, srcb, cin, is_signed, result, cout, zero_f, ov_f);
  (* src = "convert_to_v/adder.v:12.27-12.31" *)
  input [15:0] srca;
  wire [15:0] srca;
  (* src = "convert_to_v/adder.v:13.27-13.31" *)
  input [15:0] srcb;
  wire [15:0] srcb;
  (* src = "convert_to_v/adder.v:14.13-14.16" *)
  input cin;
  wire cin;
  (* src = "convert_to_v/adder.v:15.13-15.22" *)
  input is_signed;
  wire is_signed;
  (* src = "convert_to_v/adder.v:16.28-16.34" *)
  output [15:0] result;
  wire [15:0] result;
  (* src = "convert_to_v/adder.v:17.14-17.18" *)
  output cout;
  wire cout;
  (* src = "convert_to_v/adder.v:18.14-18.20" *)
  output zero_f;
  wire zero_f;
  (* src = "convert_to_v/adder.v:19.14-19.18" *)
  output ov_f;
  wire ov_f;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "convert_to_v/adder.v:23.17-23.18" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [16:0] c;
  (* src = "convert_to_v/adder.v:21.137-21.138" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78" *)
  wire [79:0] g;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71" *)
  wire [71:0] p;
  sky130_fd_sc_hd__nand2_1 _072_ (
    .A(srca[14]),
    .B(srcb[14]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _073_ (
    .A(srca[14]),
    .B(srcb[14]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _074_ (
    .A(_026_),
    .SLEEP(_027_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _075_ (
    .A(srca[13]),
    .B(srcb[13]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _076_ (
    .A(srca[11]),
    .B(srcb[11]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__and2_0 _077_ (
    .A(srca[10]),
    .B(srcb[10]),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _078_ (
    .A(srca[9]),
    .B(srcb[9]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__and2_0 _079_ (
    .A(srca[8]),
    .B(srcb[8]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(srca[8]),
    .B(srcb[8]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _081_ (
    .A(srca[7]),
    .SLEEP(srcb[7]),
    .X(_035_)
  );
  sky130_fd_sc_hd__and2_0 _082_ (
    .A(srca[7]),
    .B(srcb[7]),
    .X(_036_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _083_ (
    .A(srca[6]),
    .SLEEP(srcb[6]),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _084_ (
    .A(srca[6]),
    .B(srcb[6]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _085_ (
    .A(srca[5]),
    .B(srcb[5]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _086_ (
    .A(srca[5]),
    .B(srcb[5]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__and2_0 _087_ (
    .A(srca[4]),
    .B(srcb[4]),
    .X(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _088_ (
    .A(srca[4]),
    .B(srcb[4]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__and2_0 _089_ (
    .A(srca[3]),
    .B(srcb[3]),
    .X(_043_)
  );
  sky130_fd_sc_hd__xnor2_1 _090_ (
    .A(srca[0]),
    .B(srcb[0]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__maj3_1 _091_ (
    .A(srca[0]),
    .B(srcb[0]),
    .C(cin),
    .X(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _092_ (
    .A(srca[1]),
    .B(srcb[1]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__maj3_1 _093_ (
    .A(srca[1]),
    .B(srcb[1]),
    .C(_045_),
    .X(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _094_ (
    .A(srca[2]),
    .B(srcb[2]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__maj3_1 _095_ (
    .A(srca[2]),
    .B(srcb[2]),
    .C(_047_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _096_ (
    .A(srca[3]),
    .B(srcb[3]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _097_ (
    .A(_043_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _098_ (
    .A1(_049_),
    .A2(_051_),
    .B1(_043_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a211oi_1 _099_ (
    .A1(_049_),
    .A2(_051_),
    .B1(_041_),
    .C1(_043_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(_042_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o31ai_1 _101_ (
    .A1(_039_),
    .A2(_042_),
    .A3(_053_),
    .B1(_040_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o311ai_0 _102_ (
    .A1(_039_),
    .A2(_042_),
    .A3(_053_),
    .B1(_040_),
    .C1(_038_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a31oi_1 _103_ (
    .A1(_035_),
    .A2(_037_),
    .A3(_056_),
    .B1(_036_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a311oi_1 _104_ (
    .A1(_035_),
    .A2(_037_),
    .A3(_056_),
    .B1(_036_),
    .C1(_033_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(_034_),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _106_ (
    .A(srca[9]),
    .B(srcb[9]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _107_ (
    .A(_033_),
    .B(_034_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o31ai_1 _108_ (
    .A1(_034_),
    .A2(_058_),
    .A3(_060_),
    .B1(_032_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(srca[10]),
    .B(srcb[10]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(_031_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__maj3_1 _111_ (
    .A(srca[11]),
    .B(srcb[11]),
    .C(_031_),
    .X(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _112_ (
    .A(srca[11]),
    .B(srcb[11]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor3_1 _113_ (
    .A(_031_),
    .B(_063_),
    .C(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a21oi_1 _114_ (
    .A1(srca[9]),
    .A2(srcb[9]),
    .B1(_031_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _115_ (
    .A(srca[9]),
    .B(srcb[9]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__or3_1 _116_ (
    .A(_034_),
    .B(_058_),
    .C(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__a21oi_1 _117_ (
    .A1(_068_),
    .A2(_070_),
    .B1(_063_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a211oi_1 _118_ (
    .A1(_068_),
    .A2(_070_),
    .B1(_063_),
    .C1(_066_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a21oi_1 _119_ (
    .A1(_062_),
    .A2(_067_),
    .B1(_065_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(srca[12]),
    .B(srcb[12]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _121_ (
    .A(srca[12]),
    .B(srcb[12]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _122_ (
    .A(_002_),
    .SLEEP(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2b_1 _123_ (
    .A_N(_001_),
    .B(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(srca[13]),
    .B(srcb[13]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2b_1 _125_ (
    .A(_029_),
    .B_N(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a31oi_1 _126_ (
    .A1(_002_),
    .A2(_005_),
    .A3(_006_),
    .B1(_029_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xor2_1 _127_ (
    .A(_028_),
    .B(_008_),
    .X(result[14])
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(srca[15]),
    .B(srcb[15]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _129_ (
    .A(srca[15]),
    .B(srcb[15]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _130_ (
    .A(_009_),
    .SLEEP(_010_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(_030_),
    .B(_002_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__o21ai_0 _132_ (
    .A1(_001_),
    .A2(_003_),
    .B1(_002_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o221ai_1 _133_ (
    .A1(srca[12]),
    .A2(srcb[12]),
    .B1(_000_),
    .B2(_012_),
    .C1(_007_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a31oi_1 _134_ (
    .A1(_026_),
    .A2(_006_),
    .A3(_014_),
    .B1(_027_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xor2_1 _135_ (
    .A(_011_),
    .B(_015_),
    .X(result[15])
  );
  sky130_fd_sc_hd__xnor2_1 _136_ (
    .A(_001_),
    .B(_004_),
    .Y(result[12])
  );
  sky130_fd_sc_hd__xor2_1 _137_ (
    .A(_007_),
    .B(_013_),
    .X(result[13])
  );
  sky130_fd_sc_hd__xor2_1 _138_ (
    .A(_062_),
    .B(_064_),
    .X(result[10])
  );
  sky130_fd_sc_hd__xnor2_1 _139_ (
    .A(_066_),
    .B(_071_),
    .Y(result[11])
  );
  sky130_fd_sc_hd__xnor2_1 _140_ (
    .A(_057_),
    .B(_061_),
    .Y(result[8])
  );
  sky130_fd_sc_hd__xnor2_1 _141_ (
    .A(_059_),
    .B(_069_),
    .Y(result[9])
  );
  sky130_fd_sc_hd__a21oi_1 _142_ (
    .A1(_037_),
    .A2(_038_),
    .B1(_055_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a31oi_1 _143_ (
    .A1(_037_),
    .A2(_038_),
    .A3(_056_),
    .B1(_016_),
    .Y(result[6])
  );
  sky130_fd_sc_hd__o211a_1 _144_ (
    .A1(_036_),
    .A2(_057_),
    .B1(_056_),
    .C1(_037_),
    .X(_017_)
  );
  sky130_fd_sc_hd__a21o_1 _145_ (
    .A1(_035_),
    .A2(_057_),
    .B1(_017_),
    .X(result[7])
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(_041_),
    .B(_042_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _147_ (
    .A(_052_),
    .B(_018_),
    .Y(result[4])
  );
  sky130_fd_sc_hd__nor2b_1 _148_ (
    .A(_039_),
    .B_N(_040_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _149_ (
    .A(_054_),
    .B(_019_),
    .X(result[5])
  );
  sky130_fd_sc_hd__xnor2_1 _150_ (
    .A(_047_),
    .B(_048_),
    .Y(result[2])
  );
  sky130_fd_sc_hd__xor2_1 _151_ (
    .A(_049_),
    .B(_051_),
    .X(result[3])
  );
  sky130_fd_sc_hd__xnor2_1 _152_ (
    .A(cin),
    .B(_044_),
    .Y(result[0])
  );
  sky130_fd_sc_hd__xnor2_1 _153_ (
    .A(_045_),
    .B(_046_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__or4_1 _154_ (
    .A(result[2]),
    .B(result[3]),
    .C(result[0]),
    .D(result[1]),
    .X(_020_)
  );
  sky130_fd_sc_hd__or4_1 _155_ (
    .A(result[6]),
    .B(result[4]),
    .C(result[5]),
    .D(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__or4_1 _156_ (
    .A(result[8]),
    .B(result[9]),
    .C(result[7]),
    .D(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__or4_1 _157_ (
    .A(result[12]),
    .B(result[10]),
    .C(result[11]),
    .D(_022_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nor4_1 _158_ (
    .A(result[14]),
    .B(result[15]),
    .C(result[13]),
    .D(_023_),
    .Y(zero_f)
  );
  sky130_fd_sc_hd__o21ai_0 _159_ (
    .A1(_026_),
    .A2(_010_),
    .B1(_009_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a31o_1 _160_ (
    .A1(_028_),
    .A2(_008_),
    .A3(_011_),
    .B1(_024_),
    .X(cout)
  );
  sky130_fd_sc_hd__nand2_1 _161_ (
    .A(is_signed),
    .B(_015_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__xnor2_1 _162_ (
    .A(cout),
    .B(_025_),
    .Y(ov_f)
  );
  assign { p[71:64], p[51:48], p[33:32], p[16] } = { p[55:52], p[35:34], p[17], p[0], p[35:34], p[17], p[0], p[17], p[0], p[0] };
  assign { c[16], c[0] } = { cout, cin };
  assign { g[79:64], g[55:48], g[35:32], g[17:16], g[0] } = { cout, c[15:1], c[8:1], c[4:1], c[2:1], c[1] };
endmodule
